# Site configuration

title: 'Monstra'
description: 'Modern Open Source Flat-File Content Management System'
author:
  email: ''


# System Configuration

timezone: UTC
charset: UTF-8

theme: default

plugins:
  - Markdown

pages:
  flush_cache: false

errors:
  display: false

cache:
  enabled: false
  prefix: Monstra
  driver: auto
  lifetime: 604800
